In [1]:
import numpy as np

In [3]:
ar1=np.array([[1,2,3,4],
            [5,6,7,8]])
ar1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
#axis=0 is column-wise action
ar1.sum(axis=0)

array([ 6,  8, 10, 12])

In [5]:
#axis=1 is row-wise action
ar1.sum(axis=1)

array([10, 26])

In [6]:
ar2=np.array([[11,12,13,14],
            [15,16,17,18]])
ar2

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [7]:
#Since we are doing dot product of 2X4 with 2X4 it will give error
ar1.dot(ar2)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [9]:
a=ar2.transpose()
a

array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])

In [11]:
ar1.dot(ar2.transpose())

array([[130, 170],
       [330, 434]])

In [22]:
ar3=np.array([[22,1,19,23],
             [10,2,43,1]])
ar3

array([[22,  1, 19, 23],
       [10,  2, 43,  1]])

In [23]:
ar3.sort()
ar3

array([[ 1, 19, 22, 23],
       [ 1,  2, 10, 43]])

In [24]:
ar3.sort(axis=0)

In [25]:
ar3

array([[ 1,  2, 10, 23],
       [ 1, 19, 22, 43]])