In [1]:
#Let's import numpy

import numpy as np

#Defining an array with 1ist

array1=np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [2]:
print(type(array1))

<class 'numpy.ndarray'>


<font color="brown"> Here the type displayed is numpy.darray which is n-Dimensional array. </font>

In [4]:
#Let's define an array with a list of list

array2=np.array([[2,3,4,5],[3,4,5,6]])
print(array2)
print(type(array2))

[[2 3 4 5]
 [3 4 5 6]]
<class 'numpy.ndarray'>


In [9]:
array2.ndim

2

In [11]:
print(np.shape(array2))
array2.shape

(2, 4)


(2, 4)

In [13]:
print(np.size(array2))
array2.size

8


8

In [14]:
array2.dtype

dtype('int32')

In [21]:
array3=np.array([[11,12,0.5,14],[22,23,24,25]])
print(array3.dtype)
array3

float64


array([[11. , 12. ,  0.5, 14. ],
       [22. , 23. , 24. , 25. ]])

In [22]:
array4=np.array([[11,12,0.5,14],[22,23,24,25]], dtype="int32")
array4

array([[11, 12,  0, 14],
       [22, 23, 24, 25]])

In [15]:
array2.itemsize

4

In [16]:
array2.data

In [24]:
# Define a blank array

array5=np.zeros(4)
array5

array([0., 0., 0., 0.])

In [29]:
array6=np.zeros((4,6))
array6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

What is the purpose of using empty if the same purpose was satisfied by zeros?
With np.zeros, the value is always 0
With np.empty, mostly the values are 0 but there can be garbage values as well. It just allocates memory to the array.

In [35]:
array2

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [33]:
array2*array2

array([[ 4,  9, 16, 25],
       [ 9, 16, 25, 36]])

In [34]:
array2+array2

array([[ 4,  6,  8, 10],
       [ 6,  8, 10, 12]])

## Slicing

In [37]:
array1

array([1, 2, 3, 4])

Indexing starts with 0.

In [42]:
a=array1[2]
a

3

In [51]:
b=array1[1:]
c=array1[1:3]
print(b)
print(c)

[2 3 4]
[2 3]


In [52]:
b[1]=7

In [53]:
array1

array([1, 2, 7, 4])

In [54]:
array7=np.array([11,12,13,14,15])
array7

array([11, 12, 13, 14, 15])

In [57]:
arr=array7[0:5].copy()
print(arr)

[11 12 13 14 15]


In [60]:
arr[1]=99
print(arr)

[11 99 13 14 15]


In [61]:
array7

array([11, 12, 13, 14, 15])

In [62]:
array2

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [63]:
index_2_D=array2[0,2]
print(index_2_D)

4
