In [1]:
import numpy as np

#arange function is exactly like the range function in python. It will give an array of elements till n-1 of length n
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [2]:
b=np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
b.shape

(20,)

In [9]:
#Since the above array is a 1-D array, we can reshape the dimension of the array by using the reshape function.
#Also we cannot just use b.reshape(parameters) like sort and expect reshaping with print(b). To accomplish the task we need
#to do b=b.reshape(parameters)

b=b.reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
c=np.array([2,6,34,22,8,12,1,5,0,6,33,42,166,32,1,5,1,5,255,6,2,4])
c

array([  2,   6,  34,  22,   8,  12,   1,   5,   0,   6,  33,  42, 166,
        32,   1,   5,   1,   5, 255,   6,   2,   4])

In [11]:
#to sort the elements. But here the result shows sorting w.r.t it's index. Elements won't be in the output but the indexes of
#the elements which if sorted in an ascending order are displayed.
np.argsort(c)

array([ 8, 16, 14,  6,  0, 20, 21,  7, 15, 17,  9,  1, 19,  4,  5,  3, 13,
       10,  2, 11, 12, 18], dtype=int64)

In [12]:
np.argmin(c)

8

In [13]:
np.argmax(c)

18

We can also use argsort on Multi dimensional array

In [14]:
c=b.reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [15]:
np.argsort(c,axis=1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [16]:
np.argsort(c,axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]], dtype=int64)